plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

remote_theme: kosatyi/sjt

navigation: false
projects: true

url: https://kosatyi.com
baseurl: /xgettext-utils

brand: xgettext-utils
title: xGetText Utils
description: extract translation from source code to po files
analytics: UA-37629144-1
adsense: ca-pub-3650650669153101

author:
  name: Stepan Kosatyi
  url: https://kosatyi.com/


